name: date
on: push
jobs:
  job1:
    name: Ubuntu job
    runs-on: ubuntu-latest
    steps:
      - name: Print date
        run: date
  job2:
    name: Windows job
    runs-on: windows-latest
    steps:
      - name: Print date
        run: Get-Date
  job3:
    name: MacOs job
    runs-on: macos-latest
    steps:
      - name: Print date
        run: date
  job4:
    name: Another Ubuntu job
    runs-on: ubuntu-20.04
    needs: [job1, job2, job3]
    steps:
      - name: Print date
        run: date
