name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v5.3.0
    - name: Install requirements
      run: pip install --quiet --requirement requirements.txt
      working-directory: ./app
    - name: Lint code
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 *.py
      working-directory: ./app
    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast
      working-directory: ./app
  
  build_image:
    needs: lint
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Setup GCloud
      uses: google-github-actions/setup-gcloud@v2
    - name: Use gcloud CLI
      run: |
        gcloud auth configure-docker
        gcloud info
