name: Pipeline

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v5.3.0
    - name: Install requirements
      run: pip install --quiet --requirement requirements.txt
      working-directory: ./app
    - name: Lint code
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 *.py
      working-directory: ./app
    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast
      working-directory: ./app
  
  build_image:
    needs: lint
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: google-github-actions/auth@v2
      id: gauth
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Setup GCloud
      uses: google-github-actions/setup-gcloud@v2
    - name: Use gcloud CLI
      run: |
        gcloud auth configure-docker
        gcloud info
    - name: Build and tag image
      run: docker build -t "gcr.io/${{ steps.gauth.outputs.project_id }}/${{ env.APPLICATION_NAME }}:latest" .
      working-directory: ./app
    - name: Push to GCR
      run: docker push gcr.io/${{ steps.gauth.outputs.project_id }}/${{ env.APPLICATION_NAME }}:latest
      working-directory: ./app

  test_image:
    needs: build_image
    runs-on: ubuntu-20.04
    steps:
    - uses: google-github-actions/auth@v2
      id: gauth
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Setup GCloud
      uses: google-github-actions/setup-gcloud@v2
    - name: Use gcloud CLI
      run: |
        gcloud auth configure-docker
        gcloud info
    - name: Run unit tests in container
      run: docker run "gcr.io/${{ steps.gauth.outputs.project_id }}/${{ env.APPLICATION_NAME }}:latest" -m unittest --verbose --failfast

  deploy:
    needs: test_image
    runs-on: ubuntu-20.04
    steps:
    - uses: google-github-actions/auth@v2
      id: gauth
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - name: Setup GCloud
      uses: google-github-actions/setup-gcloud@v2
    - name: Use gcloud CLI
      run: |
        gcloud auth configure-docker
        gcloud info
    - name: Deploy to Cloud Run
      run: gcloud run deploy ${{ env.APPLICATION_NAME }} --region=us-west1 --image=gcr.io/${{ steps.gauth.outputs.project_id }}/${{ env.APPLICATION_NAME }}:latest --platform=managed --allow-unauthenticated
    - name: Test deployment
      run: |
        DEPLOY_URL=$(gcloud run services describe app2 --platform=managed --region=us-west1 | grep https)
        curl -sL --max-time 300 -o /dev/null -w "%{http_code}" $DEPLOY_URL | grep 200 || exit 1
