name: hello
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: run
      run: python ./hello.py
      working-directory: ./hello
